#! /bin/sh

xrdb -merge ~/.Xresources

export XCURSOR_THEME=miku-cursor-linux
export XCURSOR_SIZE=64
xsetroot -xcf /usr/share/icons/miku-cursor-linux/cursors/left_ptr 64 &

HOUR=$(date +%H)
if [ "$HOUR" -ge 6 ] && [ "$HOUR" -lt 18 ]; then
    feh --bg-scale /usr/share/backgrounds/Wallpapers_Icons/faPka_fields_day.png &
    bspc config focused_border_color "#0080FF"
else
    feh --bg-scale /usr/share/backgrounds/Wallpapers_Icons/faPka_fields_night.png &
    bspc config focused_border_color "#FFD700"
fi

bspc config active_border_color  "#888888"
bspc config normal_border_color  "#444444"

picom &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

for d in $(bspc query -D); do
    bspc config -d "$d" border_width 5
done

bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

killall polybar

polybar Main &
sleep 0.2 && polybar date3 &
sleep 0.2 && polybar workspaces &
sleep 0.2 && polybar cpu &
sleep 0.2 && polybar filesystem &
sleep 0.2 && polybar memory &
sleep 0.2 && polybar connections &
sleep 0.2 && polybar volume &
sleep 0.2 && polybar date &
# sleep 0.2 && polybar battery &

